POST http://localhost:7071/api/StarterFunction HTTP/1.1
Content-Type: application/json

{
    "ApprovalType" : "Email",
    "ReferenceUrl" : "test",
    "Requestor" : "mr_miyagi@gmail.com",
    "Subject" : "$2500 MacBook Approval",
    "Approver" : "damianmurawiecki@gmail.com"
}

###

POST https://durablefunctions-approval-demo.azurewebsites.net/api/StarterFunction HTTP/1.1
Content-Type: application/json

{
    "ApprovalType" : "Email",
    "ReferenceUrl" : "test",
    "Requestor" : "DMurawiecki@hoopp.com",
    "Subject" : "Request for Approval",
    "Approver" : "DMurawiecki@hoopp.com"
}