POST http://localhost:7071/api/StarterFunction HTTP/1.1
Content-Type: application/json

{
    "ApprovalType" : "Email",
    "ReferenceUrl" : "<some_return_URL>",
    "Requestor" : "mr_miyagi@gmail.com",
    "Subject" : "Test Request for Approval",
    "Approver" : "damianmurawiecki@gmail.com"
}

###

