POST http://localhost:7071/api/StarterFunction HTTP/1.1
Content-Type: application/json

{
    "ApprovalType" : "Email",
    "ReferenceUrl" : "test",
    "Requestor" : "mr_miyagi@gmail.com",
    "Subject" : "$3000 Trx Approval",
    "Approver" : "damianmurawiecki@gmail.com"
}

